name: Chore / Maintenance
description: Technical housekeeping — config, dependencies, tooling, CI, cleanup
title: "chore: "
labels: ["chore"]
body:
  - type: textarea
    id: what
    attributes:
      label: What needs to be done
      description: Describe the maintenance task clearly and specifically.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why now
      description: What risk or friction does this address? Why is this the right time?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How will we know this is done? (Checklist preferred)
      placeholder: |
        - [ ] criterion 1
        - [ ] criterion 2
    validations:
      required: true
  - type: dropdown
    id: risk
    attributes:
      label: Risk level
      description: What is the blast radius if this goes wrong?
      options:
        - Low (local dev only, no user impact)
        - Medium (CI or build affected)
        - High (affects deployed environment or data)
    validations:
      required: true
